FROM amazonlinux:2

# Before building your Docker image, make sure you have the following files in the same directory
#
# nginx-repo.crt and nginx-repo.key -- For access to install NGINX Plus
# customerCA.crt -- The issuing/signing certificate for your CloudHSM cluster
# server.crt -- the SSL certificate for your web server
# server.key -- the "fake" PEM private key generated by CloudHSM

COPY nginx-repo.* /etc/ssl/nginx/

RUN curl -L https://cs.nginx.com/static/files/nginx-plus-amazon2.repo -o /etc/yum.repos.d/nginx-plus-amazon2.repo \
 && ls -l /etc/ssl/nginx \
 && curl -L https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/EL7/cloudhsm-dyn-latest.el7.x86_64.rpm -o cloudhsm.rpm \
 && yum install nginx-plus ./cloudhsm.rpm -y \
 && ln -sf /opt/cloudhsm/lib/libcloudhsm_openssl_engine.so /usr/lib64/engines-1.1/cloudhsm.so

COPY entrypoint.sh /

# Change IP address below to your CloudHSM cluster

RUN /opt/cloudhsm/bin/configure-dyn -a 10.0.129.33 \
 && /opt/cloudhsm/bin/configure-dyn --log-level info \
 && /opt/cloudhsm/bin/configure-dyn --disable-key-availability-check \
 && chmod +x /entrypoint.sh \
 && sed -i '1 i\ssl_engine cloudhsm;\nenv CLOUDHSM_PIN;' /etc/nginx/nginx.conf \
 && ln -sf /dev/stdout /var/log/nginx/access.log \
 && ln -sf /dev/stderr /var/log/nginx/error.log

COPY customerCA.crt /opt/cloudhsm/etc
COPY server.* /etc/nginx
COPY hsm.conf /etc/nginx/conf.d

STOPSIGNAL SIGTERM
ENTRYPOINT ["/entrypoint.sh"]

